### ISSUE TITLE
HyperModal closes on inner click

### ISSUE THREAD

**Issue by mikethejet** [alekseymakhankov/hyper-modal#15]
Hi when i select the item from Select component it closes the modal. 
Its bug ? 
(using any inner react components in modal ?) 

![image](https://user-images.githubusercontent.com/2683571/67185279-bd453300-f3e5-11e9-9071-fd04a7ff0f91.png)

Thank you

**Comment by alekseymakhankov** [comment]
@mikethejet Hi, seems your dropdown is not child of modal
