### ISSUE TITLE
renderContent does not work

### ISSUE THREAD

**Issue by urielimelech** [alekseymakhankov/hyper-modal#16]
I call renderContent as a props of the HyperModal component and it does not call my function to render the content of the modal
This is what I wish to render in renderContent:
  const ModalContent = () => {
    return (
      <div>
         <button onClick={() => setIsModalOpen(false)}> OK </button>
      </div>
    )
  }

**Comment by alekseymakhankov** [comment]
Hi @urielimelech please check childrenMode property. It's true by default, set it to false to use renderContent
