### ISSUE TITLE
Fullscreen mode 

### ISSUE THREAD

**Issue by mikethejet** [alekseymakhankov/hyper-modal#18]
Hi i think the fullsceeen not works... 
![Snímek obrazovky 2020-06-19 v 15 08 43](https://user-images.githubusercontent.com/2683571/85135726-d933f980-b23e-11ea-9e04-2d6bfd25063f.jpg)

`		<HyperModal
		isFullscreen
		 renderOpenButton={(requestOpen) => {
		return (
		 <button onClick={requestOpen}>Open fullscreen modal</button>
							 );
						 }}
		 ></HyperModal>
`

I tried: 
isFullscreen
isFullscreen={true}

**Comment by alekseymakhankov** [comment]
Hi @mikethejet please check your styles. I can't reproduce the problem. Also you can check the demo
